export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_ROLE_SUCCESS = 'FETCH_USER_ROLE_SUCCESS';


export const FETCH_BUZZ_SUCCESS = 'FETCH_BUZZ_SUCCESS';

export const FETCH_COMPLAINTS_SUCCESS = 'FETCH_COMPLAINTS_SUCCESS';