export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';
export const FETCH_USER_ROLE_SUCCESS = 'FETCH_USER_ROLE_SUCCESS';
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS';

export const FETCH_BUZZ_SUCCESS = 'FETCH_BUZZ_SUCCESS';
export const FETCH_MORE_BUZZ_SUCCESS = 'FETCH_MORE_BUZZ_SUCCESS';
export const FETCH_BUZZ_FAILED = 'FETCH_BUZZ_FAILED';
export const GET_BUZZ_COUNT_SUCCESS = 'GET_BUZZ_COUNT_SUCCESS';

export const FETCH_COMPLAINTS_SUCCESS = 'FETCH_COMPLAINTS_SUCCESS';
export const FETCH_COMPLAINTS_BYUSER_SUCCESS = 'FETCH_COMPLAINTS_BYUSER_SUCCESS';
export const FETCH_ASSIGNED_COMPLAINTS_SUCCESS = 'FETCH_ASSIGNED_COMPLAINTS_SUCCESS';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_REPLIES_SUCCESS = 'FETCH_REPLIES_SUCCESS';